name: Publish

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Nuget restore necessary packages
      run: nuget restore -o packages
      
    - name: Debug build
      run: msbuild /property:Configuration=Debug
      
    - name: Release build
      run: msbuild /property:Configuration=Release
